### ISSUE TITLE
Public axis api for user management with grid?

### ISSUE THREAD

**Issue by ryan-kingstone** [Planimeter/axis#2]
Just throwing an idea out there, perhaps the "manager" could set up info tables for their users for their game, and have a "local database" for their game?

**Comment by andrewmcwatters** [comment]
Axis is schedule to be open-sourced soon, and then third-party developers will be able to do this.

**Comment by andrewmcwatters** [comment]
[axis-api](https://github.com/Planimeter/axis-api) has just been released.
